// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiEntityFramework.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? IdFormaPago { get; set; }

    public string Cliente { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}